name: PouchDB
description: PouchDB, the JavaScript Database that Syncs!
url:
markdown: redcarpet
baseurl: https://alxndrsn.github.io/pouchdb/
version: 8.0.1
paginate: 5
paginate_path: "blog/page:num"
github:
  repository_url: https://github.com/pouchdb/pouchdb
collections:
  guides:
    output: true
